### BAGGED TREES 

In [32]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale 
from sklearn import model_selection
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from warnings import filterwarnings
filterwarnings('ignore')

In [33]:
df=pd.read_csv(r"C:\Users\dilara\Downloads\miuul makine ogrenmesi\datasets\hitters.csv")
df=df.copy()
df=df.dropna()
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df["Salary"]
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size=0.25, 
                                                    random_state=42)

In [34]:
bag_model = BaggingRegressor(bootstrap_features=True)
bag_model.fit(X_train , y_train)

BaggingRegressor(bootstrap_features=True)

In [35]:
bag_model.n_estimators

10

In [36]:
bag_model.estimators_

[DecisionTreeRegressor(random_state=482656719),
 DecisionTreeRegressor(random_state=252447628),
 DecisionTreeRegressor(random_state=1418504985),
 DecisionTreeRegressor(random_state=1993913792),
 DecisionTreeRegressor(random_state=1406820326),
 DecisionTreeRegressor(random_state=1657199806),
 DecisionTreeRegressor(random_state=2110781398),
 DecisionTreeRegressor(random_state=2040519227),
 DecisionTreeRegressor(random_state=1063045833),
 DecisionTreeRegressor(random_state=101581878)]

In [37]:
bag_model.estimators_samples_

[array([158,   5, 108, 166,  49, 190,  36, 195,   4, 139, 149,  42, 117,
        158,   2, 114, 151, 121,  16, 144,  47,  77,  64, 190, 105,  72,
        179, 103,   2,  71,  42,  87, 111,  52, 129,  87,  54,  44,   4,
         92, 187, 162,  86,  93, 162, 125,  99,  58,  50,  49,  83,  86,
         36, 100, 129,  70, 153,  41,  39,   0, 160,  67, 161, 171,   2,
         43,  19, 177, 137, 131, 180, 145,  33, 151, 179,  98, 149, 109,
        187, 114,  47,  59,  38,   7, 121,  25, 184,  77,  63,  27, 129,
        143,  79,  87, 119, 140,  70,  76,  29, 136,   2, 160,   0,   7,
        140,  80, 143,  84,  30,  92,  76,  95,  15,  75, 174,  71, 167,
          3, 141, 194, 171,  34, 144, 119, 125, 130,  99, 145, 182, 149,
        193,  59, 192,  57, 108, 185,  66, 195,  79,   6, 108, 121,   6,
         56, 111, 142,  17,  45, 152, 116, 109,  17, 182, 110, 164,  10,
         82, 169, 146,  24, 142, 127, 148, 125, 185, 136, 166, 174,  69,
        192, 190,   9,  78,  29,  16,  47,  29,  23

In [38]:
bag_model.estimators_features_

[array([15, 16, 17,  1,  6,  3, 10, 12,  1, 17,  1, 14, 18, 16,  1, 10, 16,
         2, 14]),
 array([12,  5,  0, 16,  5,  3, 13, 16,  7,  9, 13, 10,  8,  5,  1,  5,  0,
        16,  4]),
 array([12, 15, 13,  1, 16,  0,  3, 17,  2,  4,  0, 13,  5, 18, 15, 18, 17,
        13,  5]),
 array([ 0,  9,  8, 15,  6,  6, 14, 10,  4, 13, 16, 13, 12,  9, 11,  1, 11,
        12, 14]),
 array([ 6,  8,  2,  7,  7,  3, 14,  1,  1,  3,  0,  0,  8,  9,  8, 16, 15,
        18,  7]),
 array([ 0,  3,  4, 13,  8,  2,  5, 16, 17,  7,  3, 15, 16,  4, 18,  6,  8,
         0, 15]),
 array([ 0,  4, 16,  6, 18, 12, 10,  6,  1, 18, 18, 13, 17,  7, 12, 11, 11,
        17,  7]),
 array([ 4, 14,  3,  1,  2,  0,  3,  1, 14, 18,  3,  2, 12, 13, 12, 18,  7,
        11, 11]),
 array([ 9,  6,  6,  2, 14, 13,  4, 17,  3, 17,  8, 15, 12,  3,  5,  0,  7,
         5, 17]),
 array([11,  3, 11,  9, 17,  7, 16,  3,  3, 14, 13, 14, 17, 17, 17,  6,  5,
        11, 17])]

In [39]:
bag_model.estimators_[0]

DecisionTreeRegressor(random_state=482656719)

## PREDICT

In [40]:
y_pred = bag_model.predict(X_test)

In [41]:
np.sqrt(mean_squared_error(y_test , y_pred))

352.3382661503859

In [42]:
iki_y_pred = bag_model.estimators_[1].fit(X_train , y_train).predict(X_test)

In [43]:
np.sqrt(mean_squared_error(y_test , iki_y_pred))

535.7337501482373

In [44]:
yedi_y_pred = bag_model.estimators_[6].fit(X_train , y_train).predict(X_test)

In [45]:
np.sqrt(mean_squared_error(y_test , yedi_y_pred))

517.7763016691492

## MODEL TUNING

In [46]:
bag_model = BaggingRegressor(bootstrap_features=True)
bag_model.fit(X_train , y_train)

BaggingRegressor(bootstrap_features=True)

In [47]:
bag_params = {"n_estimators":range(2,20)}

In [48]:
bag_cv_model = GridSearchCV(bag_model , bag_params , cv=10)

In [49]:
bag_cv_model.fit(X_train , y_train)

GridSearchCV(cv=10, estimator=BaggingRegressor(bootstrap_features=True),
             param_grid={'n_estimators': range(2, 20)})

In [50]:
bag_cv_model.best_params_

{'n_estimators': 7}

In [51]:
bag_tuned = BaggingRegressor(n_estimators=7 , random_state=45)

In [52]:
bag_tuned.fit(X_train , y_train )

BaggingRegressor(n_estimators=7, random_state=45)

In [53]:
y_pred = bag_tuned.predict(X_test)

In [54]:
np.sqrt(mean_squared_error(y_test , y_pred))

353.09815568533355